# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# Configuration file for the Sphinx documentation builder.

import os
import sys
from datetime import datetime

# Add the directory containing conf.py to the Python path
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

from generate_python_api import generate_python_api_rst
from generate_pattern_rst import generate_pattern_rst_files

for category in ["Behavioral","Structural", "Creational"]:
	generate_pattern_rst_files(
		base_dir="../../",  # Adjust if needed based on the relative path
		category=category,
		output_dir="./"  # Current directory for generated .rst files
	)

# Add the root directory of the project and its subdirectories to the Python path
sys.path.insert(0, os.path.abspath('../../'))

generate_python_api_rst()

# -- Project information -----------------------------------------------------
project = 'Design Patterns Case Study'
author = 'David Gonçalves'
copyright = f'{datetime.now().year}, {author}'
release = '1.0.0'

# -- General configuration ---------------------------------------------------
extensions = [
	'myst_parser',              # Markdown support
	'sphinx.ext.autodoc',       # Auto-generate Python documentation
	'sphinx_autodoc_typehints', # Automatically document type hints
	'sphinx.ext.napoleon',      # Support for NumPy/Google style docstrings
	'sphinx.ext.viewcode',      # Source code links
	'sphinx.ext.todo',          # TODOs in the documentation
	'sphinx.ext.intersphinx',   # Cross-referencing with external docs
]

myst_enable_extensions = [
	"linkify",      # Convert URLs to clickable links
	"substitution", # Enable text substitution
]

myst_heading_anchors = 3           # Create anchors for headings up to level 3
myst_title_to_header = True        # Use the title as the main heading
myst_update_mathjax = False        # Ensures no conflicting MathJax settings
myst_links_external_new_tab = True # Open links in a new tab

# Autodoc settings
autodoc_member_order = 'bysource'
autodoc_default_options = {
	'members': True,
	'undoc-members': False,
	'show-inheritance': True,
}
autodoc_typehints = "description"  # Show type hints both in the signature and in the description
add_module_names = False    # Remove module names from class signatures

# Napoleon settings for Google-style docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_use_param = False # already generated by sphinx_autodoc_typehints
napoleon_use_rtype = False # already generated by sphinx_autodoc_typehints

# HTML theme options
html_theme = 'sphinx_rtd_theme'
html_theme_options = {
	'navigation_depth': 4,
}

html_static_path = ['_static']  # Leave _static for additional static files

html_js_files = [
	'custom.js',  # Add your custom JavaScript file
]

# -- Intersphinx mapping -----------------------------------------------------
intersphinx_mapping = {
	'python': ('https://docs.python.org/3', None),
}

# Default role for inline code
default_role = 'code'

# -- Custom scripts ----------------------------------------------------------

# Build Javadoc
#javadoc_output = os.path.abspath('../../docs/javadoc')
#javadoc_cmd = [
	#'javadoc',
	#'-d', javadoc_output,
	#'-sourcepath', '../../Creational ../../Structural ../../Behavioral',
	#'-subpackages', '.'
#]
#subprocess.call(javadoc_cmd)

# Build Doxygen
#doxygen_output = os.path.abspath('../../docs/doxygen')
#subprocess.call(['doxygen'], cwd='../../')
