@startuml ObjectAdapter

title Object Adapter Pattern

interface Target {
    + request(): void
}

class Adaptee {
    + specificRequest(): void
}

class Adapter implements Target {
    + request(): void
    --
    - adaptee: Adaptee
}

Adapter --> Adaptee : "Delegates"

@enduml