name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-cpp:
    name: Build and Test C++ Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev

      - name: Build and test C++ code
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ctest --output-on-failure

  build-and-test-java:
    name: Build and Test Java Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'oracle'

      - name: Build and test Java code
        run: |
          gradle build
          gradle test

  build-and-test-python:
    name: Build and Test Python Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run Python tests
        run: |
          pytest

  deploy-docs:
    name: Deploy Sphinx Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'oracle'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev doxygen

      - name: Install Sphinx dependencies
        run: |
          cd docs
          pip install -U -r requirements.txt

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html

      #- name: Deploy to GitHub Pages
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: docs/build/html

      # GitHub Actions bots only have default read permissions.
      # A PAT allows it to perform write operations, such as pushing updates to the gh-pages branch.
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cd docs/build/html
          touch .nojekyll
          git init
          git add .
          git commit -m "Deploy updated documentation [skip ci]" || echo "No changes to commit"
          git branch -M gh-pages
          git remote add origin https://x-access-token:${{ secrets.GH_PAGES_TOKEN }}@github.com/${{ github.repository }}.git
          git push --force origin gh-pages